#!/usr/bin/env Rscript

options(echo=TRUE) # if you want see commands in output file
args <- commandArgs(trailingOnly = TRUE)


xx= unlist(strsplit(args, ";", fixed = FALSE, perl = FALSE, useBytes = FALSE))
inputlist <- list() 
slist  <- list() 
tlist <- list() 

for ( i in 1:length(xx)) {
	
	if( grepl("-i",xx[i]) == TRUE)
	{
		print("found i")
		print(xx[i])
		inputlist[length(inputlist)+1] <-xx[i]

	}
	if( grepl("-s",xx[i]) == TRUE)
		{
			print("found s")
			print(xx[i])
			slist[length(slist)+1] <-xx[i]

		}
	if( grepl("-t",xx[i]) == TRUE)
		{
			print("found t")
			print(xx[i])
			tlist[length(tlist)+1] <-xx[i]

		}
}

trim <- function (x) gsub("^\\s+|\\s+$", "", x)
trim2 <- function( x ) {
  gsub("(^[[:space:]]+|[[:space:]]+$)", "", x)
}

print("***************************************************")
test = gsub("-i ", "", inputlist[1])
inputFiles =""
vector = c()

for (i in 1:length(inputlist))
{
	str = gsub("-i ", "", inputlist[i])
	str = trim(str)
	print( str)
	vector[i] <- str
	inputFiles = paste(inputFiles,"'",str,"'",",")		
}

inputFiles=  substr(toString(inputFiles), 1, nchar(inputFiles)-1)
print(inputFiles)
inputFiles = paste("fileList = c(",inputFiles,")")
inputFiles = trim2(inputFiles)
print(inputFiles)
print(vector)


sampleId =""
for (i in 1:length(slist))
{	
	slisttr = gsub("-s ", "", slist[i])
	slisttr = trim(slisttr)
	sampleId = paste(sampleId,slisttr,",")		
}

sampleId=  substr(toString(sampleId), 1, nchar(sampleId)-1)
sampleId = paste("c(",sampleId,")")
sampleId = trim(sampleId)


treat= ""
for (i in 1:length(tlist))
{
	print(tlist[i])
	tlisttr = gsub("-t", "", tlist[i])
	tlisttr = trim(tlisttr)
	treat = paste(treat,tlisttr,",")		
}
treat=  substr(toString(treat), 1, nchar(treat)-1)
treat = paste("c(",treat,")")
treat= trim(treat)

print(inputFiles)
print (treat)
print (sampleId)
print(inputFiles)
library(methylSig)
meth <- methylSigReadData(inputFiles, sample.ids = sampleId, assembly = "hg18",treatment = treat, context = "CpG", destranded=TRUE)
mydata = read.table(trim(gsub("-i ", "", inputlist[1])))
print(mydata)

